<div style='float: left;width: 45%;margin-left:10px;'>Erreur php</div>
<div style='float: left;width: 45%;margin-left:10px;'>Erreur zend</div>
<div style='background-color: white;color: black;white-space: pre;float: left;width: 45%;max-height:400px;overflow: auto;margin-left:10px;font-size: 11px;border:solid 1px '>
<?= $this->php_error;?>
</div>

<div style='background-color: white;color: black;white-space: pre;float: left;width: 45%;max-height:400px;overflow: auto;margin-left:10px;'>
<?= $this->zend_error;?>
</div>