<?php echo $this->formButton("add","Ajouter un livreur",array("onclick"=>"location.href='".$this->url(array("controller"=>"contact","action"=>"add","module"=>"admin","is_liv"=>1))."'")); ?>
    <label for='search'>Recherche : </label><?php echo $this->formText("search","",array("onkeyup"=>'search_liv(this.value,1)'));?>
<div id='contact' style='height:550px;width:550px;overflow:auto;clear:both'>
    <?php foreach($this->list as $li ){

        if($li->is_fav==1)
            echo "<img src='".$this->BaseUrl("/images/star.gif")."' style='float:left'/>";
    echo"
    <span style='display:inline-block;width:auto;margin-right:10px;float:left'> $li->nom_livreur - $li->tel_livreur </span>";
echo  $this->formButton("delete_".$li->id_livreur,"Supprimer",array("onclick"=>"location.href='".$this->url(array("controller"=>"contact","action"=>"delete","module"=>"admin","id_livreur"=>$li->id_livreur,"is_liv"=>$li->is_liv))."'","style"=>"float:right"));
    echo $this->formButton("update_".$li->id_livreur,"Modifier",array("onclick"=>"location.href='".$this->url(array("controller"=>"contact","action"=>"update","module"=>"admin","id_livreur"=>$li->id_livreur,"is_liv"=>$li->is_liv))."'",
        "style"=>"float:right"));



    echo "<br/><hr style='margin:0px;width:550px;'/><br/>";

    }?>
</div>