<?php ob_start();
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
echo $this->doctype(); ?>
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
<head>
 <?php echo $this->headMeta();?>
    </head>
<body>
  
  <?php echo $this->layout()->content; ?>
  <script type='text/javascript'>//print();
    <?php if($this->config->module_print && $this->config->os=="win"){ ?>
      jsPrintSetup.setPrinter('<?= $this->config->printer; ?>');
    jsPrintSetup.setOption('marginTop', 0);
    jsPrintSetup.setOption('marginBottom', 0);
    jsPrintSetup.setOption('marginLeft', 0);
    jsPrintSetup.setOption('marginRight', 0);
    jsPrintSetup.setOption('headerStrLeft', '');
    jsPrintSetup.setOption('headerStrCenter', '');
    jsPrintSetup.setOption('headerStrRight', '');
    // set empty page footer
    jsPrintSetup.setOption('footerStrLeft', '');
    jsPrintSetup.setOption('footerStrCenter', '');
    jsPrintSetup.setOption('footerStrRight', '');

    // clears user preferences always silent print value
    // to enable using 'printSilent' option
    jsPrintSetup.clearSilentPrint();
    // Suppress print dialog (for this context only)
    jsPrintSetup.setOption('printSilent', 1);

        jsPrintSetup.print();
    <?php }
    ?>
    //  jsPrintSetup. setShowPrintProgress(oldShowPrintProgress);
  // window.close();
</script>
    </body>
</html>