<table id='list_cmd_global' style='border:none 0px;'>
  <tr >
    <td colspan='2' style='border:none 0px;'>
      <?php
      echo $this->formButton("print", "Imprimer", array("onclick"=>"window.open('".$this->url(array("action"=>"printMonth",
              "controller"=>"chiffre",
              "month"=>date("Y-m", strtotime($this->date_cmd))))."')"));
      ?>
    </td>
  </tr>
  <tr>
    <td style='border:none 0px;'>
      <table style='border:none 0px;'>
        <tr>
          <th>Date de la Commande</th>

          <th style='width:75px'>Total</th>

        </tr>
        <?php
        foreach($this->cmdMonth as $cmd){
          echo "<tr >
            <td style='text-align:center;font-weight:bold'>";
          echo date("d", strtotime($cmd->date_cmd))." ".$this->month[date("n", strtotime($cmd->date_cmd))]." ".date("Y", strtotime($cmd->date_cmd));

          echo "</td>
        <td valign='top'>".number_format($cmd->total, 2, ",", " ")." &euro;</td>
        </tr>";
        }
        ?>

      </table>
    </td>
    <td style='border:none 0px;'>
      <table>
        <tr>
          <th style='width:75px' colspan='2'>Détail des paiements</th>
            <?php
            foreach($this->RecapReglement as $k=> $reg){
              echo "<tr >
            <td style='text-align:left;font-weight:bold'>";
              echo $this->tabReglement[$k];

              echo "</td>
        <td valign='top'>".number_format($reg, 2, ",", " ")." &euro;</td>
        </tr>";
            }
            ?>
        </tr>
      </table>
    </td>
</table>